-- 1. Create the physical target Staging Tables
CREATE TABLE IF NOT EXISTS STG_PARTNERS (
    HK_PARTNER_HASH TEXT PRIMARY KEY,
    PARTNER_ID TEXT NOT NULL,
    COMPANY_NAME TEXT,
    CITY TEXT,
    LOAD_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    RECORD_SOURCE TEXT NOT NULL
);

-- 2. Clean, Hash, and Load from the Raw CSV Landed Table
INSERT OR REPLACE INTO STG_PARTNERS (HK_PARTNER_HASH, PARTNER_ID, COMPANY_NAME, CITY, LOAD_TIMESTAMP, RECORD_SOURCE)
WITH clean_source AS (
    SELECT 
        UPPER(TRIM(COALESCE(PARTNER_ID, 'UNKNOWN'))) AS clean_id,
        TRIM(COMPANY_NAME) AS COMPANY_NAME,
        TRIM(CITY) AS CITY
    FROM src_csv_partners
    WHERE PARTNER_ID IS NOT NULL -- Ensure valid IDs
)
SELECT 
    -- Compute the MD5 Hash (requires MD5 support in the database)
    HEX(SUBSTR(clean_id, 1, 32)) AS HK_PARTNER_HASH, 
    clean_id AS PARTNER_ID,
    COMPANY_NAME,
    CITY,
    CURRENT_TIMESTAMP AS LOAD_TIMESTAMP,
    'CSV_PORTAL' AS RECORD_SOURCE
FROM clean_source;